from pygame.constants import *

class Constants:
	PRIMITIVE_RECTANGLE=0
	PRIMITIVE_CIRCLE=1

	ASSET_TYPE_NONE=0
	ASSET_TYPE_IMAGE=1
	ASSET_TYPE_SHADER=2

	INDEX_TRANSFORM=0
	INDEX_PRIMITIVE=1
	INDEX_IMAGE=2
	
	KEY_LUT = (
		"BACKSPACE","TAB","CLEAR","RETURN","PAUSE","ESCAPE","SPACE","EXCLAIM","QUOTEDBL","HASH",
		"DOLLAR","AMPERSAND","QUOTE","LEFTPAREN","RIGHTPAREN","ASTERISK","PLUS","COMMA","MINUS","PERIOD",
		"SLASH","0","1","2","3","4","5","6","7","8","9","COLON","SEMICOLON","LESS","EQUALS",
		"GREATER","QUESTION","AT","LEFTBRACKET","BACKSLASH","RIGHTBRACKET","CARET","UNDERSCORE","BACKQUOTE",
		"a","b","c","d","e","f","g","h","i","j","k","l","m","n","o","p","q","r","s","t","u","v","w","x","y","z",
		"DELETE","KP0","KP1","KP2","KP3","KP4","KP5","KP6","KP7","KP8","KP9","KP_PERIOD","KP_DIVIDE","KP_MULTIPLY",
		"KP_MINUS","KP_PLUS","KP_ENTER","KP_EQUALS","UP","DOWN","RIGHT","LEFT","INSERT","HOME","END","PAGEUP","PAGEDOWN",
		"F1","F2","F3","F4","F5","F6","F7","F8","F9","F10","F11","F12","F13","F14","F15","NUMLOCK","CAPSLOCK","SCROLLLOCK",
		"RSHIFT","LSHIFT","RCTRL","LCTRL","RALT","LALT","RMETA","LMETA","LSUPER","RSUPER",
		"MODE","HELP","PRINT","SYSREQ","BREAK","MENU","POWER","EURO","AC_BACK",
	)
	KEY_CODE_LUT = (
		("BACKSPACE",K_BACKSPACE),("TAB",K_TAB),("CLEAR",K_CLEAR),("RETURN",K_RETURN),("PAUSE",K_PAUSE),("ESCAPE",K_ESCAPE),
		("SPACE",K_SPACE),("EXCLAIM",K_EXCLAIM),("QUOTEDBL",K_QUOTEDBL),("HASH",K_HASH),("DOLLAR",K_DOLLAR),("AMPERSAND",K_AMPERSAND),
		("QUOTE",K_QUOTE),("LEFTPAREN",K_LEFTPAREN),("RIGHTPAREN",K_RIGHTPAREN),("ASTERISK",K_ASTERISK),("PLUS",K_PLUS),("COMMA",K_COMMA),
		("MINUS",K_MINUS),("PERIOD",K_PERIOD),("SLASH",K_SLASH),("0",K_0),("1",K_1),("2",K_2),("3",K_3),("4",K_4),("5",K_5),("6",K_6),
		("7",K_7),("8",K_8),("9",K_9),("COLON",K_COLON),("SEMICOLON",K_SEMICOLON),("LESS",K_LESS),("EQUALS",K_EQUALS),("GREATER",K_GREATER),
		("QUESTION",K_QUESTION),("AT",K_AT),("LEFTBRACKET",K_LEFTBRACKET),("BACKSLASH",K_BACKSLASH),("RIGHTBRACKET",K_RIGHTBRACKET),
		("CARET",K_CARET),("UNDERSCORE",K_UNDERSCORE),("BACKQUOTE",K_BACKQUOTE),("a",K_a),("b",K_b),("c",K_c),("d",K_d),("e",K_e),("f",K_f),
		("g",K_g),("h",K_h),("i",K_i),("j",K_j),("k",K_k),("l",K_l),("m",K_m),("n",K_n),("o",K_o),("p",K_p),("q",K_q),("r",K_r),("s",K_s),
		("t",K_t),("u",K_u),("v",K_v),("w",K_w),("x",K_x),("y",K_y),("z",K_z),("DELETE",K_DELETE),("KP0",K_KP0),("KP1",K_KP1),("KP2",K_KP2),
		("KP3",K_KP3),("KP4",K_KP4),("KP5",K_KP5),("KP6",K_KP6),("KP7",K_KP7),("KP8",K_KP8),("KP9",K_KP9),("KP_PERIOD",K_KP_PERIOD),
		("KP_DIVIDE",K_KP_DIVIDE),("KP_MULTIPLY",K_KP_MULTIPLY),("KP_MINUS",K_KP_MINUS),("KP_PLUS",K_KP_PLUS),("KP_ENTER",K_KP_ENTER),("KP_EQUALS",K_KP_EQUALS),
		("UP",K_UP),("DOWN",K_DOWN),("RIGHT",K_RIGHT),("LEFT",K_LEFT),("INSERT",K_INSERT),("HOME",K_HOME),("END",K_END),("PAGEUP",K_PAGEUP),("PAGEDOWN",K_PAGEDOWN),
		("F1",K_F1),("F2",K_F2),("F3",K_F3),("F4",K_F4),("F5",K_F5),("F6",K_F6),("F7",K_F7),("F8",K_F8),("F9",K_F9),("F10",K_F10),("F11",K_F11),
		("F12",K_F12),("F13",K_F13),("F14",K_F14),("F15",K_F15),("NUMLOCK",K_NUMLOCK),("CAPSLOCK",K_CAPSLOCK),("SCROLLLOCK",K_SCROLLLOCK),
		("RSHIFT",K_RSHIFT),("LSHIFT",K_LSHIFT),("RCTRL",K_RCTRL),("LCTRL",K_LCTRL),("RALT",K_RALT),("LALT",K_LALT),("RMETA",K_RMETA),("LMETA",K_LMETA),
		("LSUPER",K_LSUPER),("RSUPER",K_RSUPER),("MODE",K_MODE),("HELP",K_HELP),("PRINT",K_PRINT),("SYSREQ",K_SYSREQ),("BREAK",K_BREAK),("MENU",K_MENU),
		("POWER",K_POWER),("EURO",K_EURO),("AC_BACK",K_AC_BACK)
	)

	KEY_MOD_CODE_LUT = ("NONE","LSHIFT","RSHIFT","SHIFT","LCTRL","RCTRL","CTRL","LALT","RALT","ALT","LMETA","RMETA","META","CAPS","NUM","MODE")

	KEY_MOD_CODE_LUT = {
		("NONE",KMOD_NONE),("LSHIFT",KMOD_LSHIFT),("RSHIFT",KMOD_RSHIFT),("SHIFT",KMOD_SHIFT),("LCTRL",KMOD_LCTRL),("RCTRL",KMOD_RCTRL),("CTRL",KMOD_CTRL),("LALT",KMOD_LALT),
		("RALT",KMOD_RALT),("ALT",KMOD_ALT),("LMETA",KMOD_LMETA),("RMETA",KMOD_RMETA),("META",KMOD_META),("CAPS",KMOD_CAPS),("NUM",KMOD_NUM),("MODE",KMOD_MODE)
	}